// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(FilmLoWebAppContext))]
    partial class FilmLoWebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Friendship", b =>
                {
                    b.Property<long>("UserRecipientId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserSenderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FriendshipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusCodeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("UserRecipientId", "UserSenderId");

                    b.HasIndex("StatusCodeID");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Friendship");
                });

            modelBuilder.Entity("Domain.MovieDetailsJMDBApi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MovieDetailsJMDBApi");
                });

            modelBuilder.Entity("Domain.MovieJMDBApi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MovieJMDBApi");
                });

            modelBuilder.Entity("Domain.SavedMovie", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("MovieJMDBApiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SavingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "MovieJMDBApiId");

                    b.HasIndex("MovieJMDBApiId");

                    b.ToTable("SavedMovie");
                });

            modelBuilder.Entity("Domain.StatusCode", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("StatusCode");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MovieDetailsJMDBApiId")
                        .HasColumnType("bigint");

                    b.Property<string>("MovieJMDBApiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MovieDetailsJMDBApiId");

                    b.HasIndex("MovieJMDBApiId");

                    b.HasIndex("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain.WatchedMovie", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("MovieDetailsJMDBApiId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieDetailsJMDBApiId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("WatchingDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "MovieDetailsJMDBApiId");

                    b.HasIndex("MovieDetailsJMDBApiId1");

                    b.ToTable("WatchedMovie");
                });

            modelBuilder.Entity("Domain.Friendship", b =>
                {
                    b.HasOne("Domain.StatusCode", "StatusCode")
                        .WithMany("Friendships")
                        .HasForeignKey("StatusCodeID")
                        .HasConstraintName("FK_Friendship_StatusCode")
                        .IsRequired();

                    b.HasOne("Domain.User", "UserRecipient")
                        .WithMany()
                        .HasForeignKey("UserRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "UserSender")
                        .WithMany()
                        .HasForeignKey("UserSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.MovieDetailsJMDBApi", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany("WatchedMovies")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.MovieJMDBApi", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany("SavedMovies")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.SavedMovie", b =>
                {
                    b.HasOne("Domain.MovieJMDBApi", "MovieJMDBApi")
                        .WithMany()
                        .HasForeignKey("MovieJMDBApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.HasOne("Domain.MovieDetailsJMDBApi", null)
                        .WithMany("Users")
                        .HasForeignKey("MovieDetailsJMDBApiId");

                    b.HasOne("Domain.MovieJMDBApi", null)
                        .WithMany("Users")
                        .HasForeignKey("MovieJMDBApiId");

                    b.HasOne("Domain.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.WatchedMovie", b =>
                {
                    b.HasOne("Domain.MovieJMDBApi", "MovieDetailsJMDBApi")
                        .WithMany()
                        .HasForeignKey("MovieDetailsJMDBApiId1");

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
